### ISSUE TITLE
How to play

### ISSUE THREAD

**Issue by Sahelantrophus** [MaximumADHD/Super-Nostalgia-Zone#2]

**Comment by Sahelantrophus** [comment]
Very helpful thank you👍

**Comment by MaximumADHD** [comment]
it’s a rojo project, check the README next time ;)

**Comment by Sahelantrophus** [comment]
you're fat, eat a SALAD next time ;)

**Comment by Sahelantrophus** [comment]
mb i got mad in cs2 and i had to take it out on someone
